In [7]:
import pandas as pd

myData = pd.read_csv("COVID-19_Dataset.csv")
myData.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [8]:
myData.shape

(1048575, 21)

In [14]:
medical_variables = [
    "DIABETES",
    "COPD",
    "ASTHMA",
    "INMSUPR",
    "HIPERTENSION",
    "CARDIOVASCULAR",
    "RENAL_CHRONIC",
    "OTHER_DISEASE",
    "OBESITY",
    "TOBACCO"
]

In [15]:
myData[medical_variables] = myData[medical_variables].replace([97, 99], pd.NA)
myData[medical_variables] = myData[medical_variables].fillna("Unknown")

In [16]:
myData[medical_variables].head()

,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,CARDIOVASCULAR,RENAL_CHRONIC,OTHER_DISEASE,OBESITY,TOBACCO
0,2,2,2,2,1,2,2,2,2,2
1,2,2,2,2,1,2,1,2,1,2
2,1,2,2,2,2,2,2,2,2,2
3,2,2,2,2,2,2,2,2,2,2
4,1,2,2,2,1,2,2,2,2,2

In [18]:
demo_variables = [
    "SEX",
    "AGE",
    "PREGNANT"
]

In [19]:
myData[demo_variables] = myData[demo_variables].replace([97, 99], pd.NA)
myData[demo_variables] = myData[demo_variables].fillna("Unknown")

In [20]:
myData[demo_variables].head()

   SEX AGE PREGNANT
0    1  65        2
1    2  72  Unknown
2    2  55  Unknown
3    1  53        2
4    2  68  Unknown